### ISSUE TITLE
Errore durante la riproduzione degli episodi scaricati

### ISSUE THREAD

**Issue by SweatierKey** [fexh10/aw-cli#1]
### Descrizione dell'errore
Quando provo a riprodurre un episodio tra quelli che ho scaricato vlc non parte e la console riporta un errore.
Questo comportamento non si verifica quando invece l'episodio che cerco di riprodurre non e' scaricato.

### Informazioni Generali
**Python version:** Python 3.11.3
**Vlc version:** 3.0.18 Vetinari
**Operating System:** Windows 11
**Terminale utilizzato:** Windows PowerShell

### Output della console (Errore)
L'errore riportato sotto e' l'errore che ricevo quando provo a riprodurre un episodio scaricato
![Screenshot 2023-06-04 193504](https://github.com/fexh10/aw-cli/assets/53280918/72864409-d877-4d41-95b0-5e878c537793)

```
Riproduco Hell’s Paradise (ITA) Ep. 2...
Carattere di terminazione mancante nella stringa: '.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pywinauto\application.py", line 958, in connect
    wait_until(timeout, retry_interval, self.is_process_running, value=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pywinauto\timings.py", line 375, in wait_until
    raise err
pywinauto.timings.TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Scripts\aw-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\awcli\run.py", line 591, in main
    openVideos(ep_iniziale,ep_finale, mpv, tokenAnilist, ratingAnilist, preferitoAnilist)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\awcli\run.py", line 346, in openVideos
    openMPV(url_server, nome_video) if mpv else openVLC(url_server, nome_video)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\awcli\run.py", line 231, in openVLC
    isRunning("vlc.exe")
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\awcli\run.py", line 164, in isRunning
    app = Application().connect(process=pid)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pywinauto\application.py", line 960, in connect
    raise ProcessNotFoundError('Process with PID={} not found!'.format(self.process))
pywinauto.application.ProcessNotFoundError: Process with PID=0 not found!
```

### Comportamento con episodi non scaricati.
Come specificato precedentemente quando si riproduce un episodio non scaricato questo viene riprodotto correttamente e riporta il seguente messaggio in console:

![Screenshot 2023-06-04 193739](https://github.com/fexh10/aw-cli/assets/53280918/603d85e3-5bf1-477d-80f2-41ba324caeeb)
`Riproduco One Piece Movie 15: Red (ITA) Ep. 1...`

E vlc si apre correttamente visualizzando l'episodio scelto, la console rivela anche la chiusura di vlc riportando il seguente messaggio:

![Screenshot 2023-06-04 194005](https://github.com/fexh10/aw-cli/assets/53280918/e6911264-f153-46dd-8ea1-c2a91de455d9)
```
Seleziona una risposta valida
(r) riguarda
(i) indietro
(e) esci
>
```

Non so esattamente cosa possa causare questo errore, non ne ho le competenze purtroppo, ma spero che le informazioni fornite possano aiutare,

Grazie.

**Comment by fexh10** [comment]
Grazie per la segnalazione. Sono riuscito a riprodurre l'errore e ho provveduto alla correzione dell'errore nell'ultimo commit. Puoi cancellare la versione attuale con `pip uninstall aw-cli` e installare quella più recente con `python3 -m pip install git+https://github.com/fexh10/aw-cli.git`

**Comment by SweatierKey** [comment]
Grazie mille, confermo che ora funziona, riesco a riprodurre gli episodi scaricati.
