### ISSUE TITLE
iOS problema

### ISSUE THREAD

**Issue by VenomDrake** [fexh10/aw-cli#10]
Quando cerco di avviare aw-cli mi da questo errore.

localhost:~# aw-cli                                                                                        
Traceback (most recent call last):                                                                         
  File "/usr/bin/aw-cli", line 33, in <module>                                                             
    sys.exit(load_entry_point('aw-cli==1.8.1', 'console_scripts', 'aw-cli')())                             
  File "/usr/lib/python3.9/site-packages/awcli/run.py", line 604, in main                                  
    if nome_os != "Android" and args.syncpl:                                                               
AttributeError: 'Namespace' object has no attribute 'syncpl'

**Comment by fexh10** [comment]
Dovrei essere riuscito a correggere l'errore nell'ultimo commit del branch iosCompatibility, puoi provare a reinstallare il programma con lo stesso comando

**Comment by VenomDrake** [comment]
Ciao Fexh ho riprovato ma nulla mi da questo.

Traceback (most recent call last):
  File "/usr/bin/aw-cli", line 33, in <module>
    sys.exit(load_entry_point('aw-cli==1.8.1', 'console_scripts', 'aw-cli')())
  File "/usr/lib/python3.9/site-packages/awcli/run.py", line 604, in main
    if nome_os != "Android" and args.syncpl:
AttributeError: 'Namespace' object has no attribute 'syncpl'
