### ISSUE TITLE
Non e' possibile scaricare anime che nel titolo hanno i due punti ":"

### ISSUE THREAD

**Issue by SweatierKey** [fexh10/aw-cli#2]
Quando provo a scaricare un anime che ha nel nome i due punti ":" ovviamente il programma non riesce a creare la cartella perche' deve trattarsi di un carattere che non puo' essere usato su Windows per la creazione di cartelle.

## Errore riscontrato

![image](https://github.com/fexh10/aw-cli/assets/53280918/c18527fd-0ddb-4c2c-86de-50e1aabcddb9)
```
Mashle: Magic and Muscles (ITA)
Specifica un episodio, o per un range usa: ep_iniziale-ep_finale (Episodi: 1-6)
> 1-6
Mashle: Magic and Muscles (ITA) Ep. 1:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Scripts\aw-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\awcli\run.py", line 580, in main
    scaricaEpisodio(ep, path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\awcli\run.py", line 140, in scaricaEpisodio
    SDL = SmartDL(url_ep, f"{path}/{nome_video}.mp4")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pySmartDL\pySmartDL.py", line 135, in __init__
    os.makedirs(os.path.dirname(self.dest))
  File "<frozen os>", line 225, in makedirs
NotADirectoryError: [WinError 267] Nome di directory non valido: 'C:\\Users\\user/Videos/Anime/Mashle: Magic and Muscles (ITA)'
PS C:\Users\user>
```

## Informazioni generali
Sistema Operativo: Windows 11

Non so esattamente come si potrebbe risolvere questa problematica, probabilmente va' aggiunto un pezzo di codice che controlla la presenza di ":" nel titolo dell'anime e lo rimuova o sostituisca con qualcos'altro.

Ho trovato [questo thread](https://stackoverflow.com/questions/10386344/how-to-get-a-file-in-windows-with-a-colon-in-the-filename) su stackoverflow che forse potrebbe aiutare.

Grazie.

**Comment by fexh10** [comment]
Grazie a te. Dovrei aver corretto l'errore nell'ultimo commit.

**Comment by SweatierKey** [comment]
Confermo che funziona👍.
Grazie mille.
